config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :items do
    resources :comments
  end
  resources :stocks, only: [:create, :destroy]
  root 'items#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :item
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user
  has_many :stocks
  has_many :comments
  acts_as_taggable
end

app/models/stock.rb
class Stock < ActiveRecord::Base
  belongs_to :user
  belongs_to :item
  validates :user_id,
    uniqueness: {
      message: "すでにStock済みです",
      scope: [:item_id]
  }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :items
  has_many :stocks
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = current_user.comments.new(comment_params.merge(item_id: params[:item_id]))
    comment.save
    redirect_to item_url(params[:item_id])
  end

  def destroy

  end
  
  private
  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :set_item_tags_to_gon, only: [:edit]
  before_action :set_available_tags_to_gon, only: [:new, :edit]

  def index
    @items = Item.all
  end

  def show
    @stock = current_user.stocks.find_by(item_id: @item)
    @comment = current_user.comments.new
    @comments = @item.comments
    if @stock.blank?
      @stock = current_user.stocks.new
    end
  end

  def new
    @item = current_user.items.new
  end

  def edit
  end

  def create
    @item = current_user.items.new(item_params)
    if @item.save
      redirect_to @item, notice: 'レコードを作成しました。'
    else 
      render :new
    end
  end

  def update
    if @item.update(item_params)
      redirect_to @item, notice: 'レコードを更新しました。'
    else
      render :edit
    end
  end

  def destroy
    @item.destroy
    redirect_to items_url, notice: '削除しました'
  end

  private
    def set_item
      @item = Item.find(params[:id])
    end

    def item_params
      params.require(:item).permit(:title, :content, :tag_list)
    end

    def set_item_tags_to_gon
      gon.item_tags = @item.tag_list
    end

    def set_available_tags_to_gon
      gon.available_tags = Item.tags_on(:tags).pluck(:name)
    end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  def create
    @stock = current_user.stocks.new(stock_params)
    @stock.save
  end

  def destroy
    @stock = current_user.stocks.find(params[:id])
    @stock.destroy
  end

  private
  def stock_params
    params.require(:stock).permit(:item_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/comments/_comment.html.haml
.comment
  .user
    = comment.user.name
  .created
    = comment.created_at
  .content
    = comment.content

app/views/comments/_form.html.haml
= form_for [@item, @comment] do |f|
  - if @comment.errors.any?
    #error_explanation
      %h2= "#{pluralize(@comment.errors.count, "error")}"
      %ul
        - @comment.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :content
    = f.text_area :content
  .actions
    = f.submit 'Comment'

app/views/items/_form.html.haml
= form_for @item do |f|
  - if @item.errors.any?
    #error_explanation
      %h2= "#{pluralize(@item.errors.count, "error")}"
      %ul
        - @item.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :content
    = f.text_area :content
  .field
    %ul#item-tags
  .actions
    = f.submit 'Save'

app/views/items/edit.html.haml
%h1 編集

= render 'form'

= link_to 'Show', @item
\|
= link_to 'Back', items_path

app/views/items/index.html.haml
%h1 Items

%table
  %thead
    %tr
      %th Title
      %th Content
      %th
      %th
      %th
  %tbody
    - @items.each do |item|
      %tr
        %td=item.title
        %td=item.content
        %td=link_to 'Show', item 
        %td=link_to 'Edit', edit_item_path(item)
        %td=link_to 'Delete', item, method: :delete, :data => { confirm: '本当にいいですか？'}

%br
=link_to 'New', new_item_path

app/views/items/new.html.haml
%h1 新規作成

= render 'form'

= link_to 'Back', items_path

app/views/items/show.html.haml
%p#notice= notice
%h1= @item.title
%p= @item.content

#stock-link
  - if @stock.id.present?
    = render partial: 'stocks/unstock', locals: { stock: @stock }
  - else
    = render partial: 'stocks/stock', locals: { item: @item }

= render 'comments/form'
= render partial: 'comments/comment', collection: @comments

= link_to 'Edit', edit_item_path(@item)
\|
= link_to 'Back', items_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title MuraQiita3
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = Gon::Base.render_data
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = yield

app/views/stocks/_stock.html.haml
= link_to 'Stock', stocks_path(stock: {item_id: item}), method: :post, remote: true

app/views/stocks/_unstock.html.haml
= link_to 'unStock', stock, method: :delete, remote: true

app/views/stocks/create.js.haml
$('#stock-link').html("#{j(render partial: 'stocks/unstock', locals: { stock: @stock })}")

app/views/stocks/destroy.js.haml
$('#stock-link').html("#{j(render partial: 'stocks/stock', locals: { item: @item })}")

app/views/users/shared/_links.html.haml
- if controller_name != 'sessions'
  = link_to "Log in", new_session_path(resource_name)
  %br/
- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to "Sign up", new_registration_path(resource_name)
  %br/
- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
  = link_to "Forgot your password?", new_password_path(resource_name)
  %br/
- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)
  %br/
- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)
  %br/
- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider)
    %br/